# Replace name with your own app name
name = "cloudflare-status-template"
main = "src/index.tsx"
compatibility_date = "2024-06-03"
compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "DB"
# Replace with your own database name and ID.
database_name = "cloudflare-status-template"
database_id = "8c154625-a86a-4825-9ec6-8d81dd2f4cbd"

[triggers]
# Configure the CRON schedules, ensure the probes in src/probes/probe-configs.ts are configured accordingly
crons = [ "0 * * * *" ]
